//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using DoAnQLPM.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class BenhNhan : BaseViewModel
    {
        public BenhNhan()
        {
            this.PhieuKBs = new HashSet<PhieuKB>();
        }

        private int _MaBN;
        public int MaBN { get { return _MaBN; } set { _MaBN = value; OnPropertyChanged(); } }
        private string _HoVaTen;
        public string HoVaTen { get { return _HoVaTen; } set { _HoVaTen = value; OnPropertyChanged(); } }
        private string _GioiTinh;
        public string GioiTinh { get { return _GioiTinh; } set { _GioiTinh = value; OnPropertyChanged(); } }
        private int _NamSinh;
        public int NamSinh { get { return _NamSinh; } set { _NamSinh = value; OnPropertyChanged(); } }
        private string _DiaChi;
        public string DiaChi { get { return _DiaChi; } set { _DiaChi = value; OnPropertyChanged(); } }
    
        public virtual ICollection<PhieuKB> PhieuKBs { get; set; }
    }
}
