//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan
    {
        public BenhNhan()
        {
            this.PhieuKBs = new HashSet<PhieuKB>();
        }
    
        public string MaBN { get; set; }
        public string MaPhieuKhamBenh { get; set; }
        public string HoVaTen { get; set; }
        public string GioiTinh { get; set; }
        public int NamSinh { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<PhieuKB> PhieuKBs { get; set; }
    }
}
