//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public int MaPKB { get; set; }
        public double TienKham { get; set; }
        public double TienThuoc { get; set; }
        public double TongTien { get; set; }
    
        public virtual PhieuKB PhieuKB { get; set; }
    }
}
