//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKB
    {
        public PhieuKB()
        {
            this.CTPhieuKBs = new HashSet<CTPhieuKB>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaPKB { get; set; }
        public int MABN { get; set; }
        public int MaBenh { get; set; }
        public string TrieuChung { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<double> TienKham { get; set; }
    
        public virtual Benh Benh { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual ICollection<CTPhieuKB> CTPhieuKBs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
