//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKB
    {
        public PhieuKB()
        {
            this.CHITIETPKBs = new HashSet<CHITIETPKB>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int id { get; set; }
        public string MaPKB { get; set; }
        public string MaBN { get; set; }
        public string LoaiBenh { get; set; }
        public string TrieuChung { get; set; }
        public System.DateTime NgayKham { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual ICollection<CHITIETPKB> CHITIETPKBs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
