//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string username { get; set; }
        public string tenhienthi { get; set; }
        public string password { get; set; }
        public int TYPE { get; set; }
    }
}
