//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public Thuoc()
        {
            this.CHITIETPKBs = new HashSet<CHITIETPKB>();
        }
    
        public int MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string DonVi { get; set; }
        public int DonGia { get; set; }
    
        public virtual ICollection<CHITIETPKB> CHITIETPKBs { get; set; }
    }
}
